language: python

# Далее, укажите версии python для которых нужно производить сборки
python:
  - "3.4"
  - "3.5"


# Команда для установки зависимостей в окружение (при этом доступны переменные из секции "env")
install:
  - pip install -r requirements.txt
  - pip install coveralls

# Команда для запуска тестов, в моем случае они запускаются именно так
script:
    coverage run -m pytest

after_success:
    coveralls
